# Properties of Dot Product - Lab

## Introduction

In this lab, you'll be practicing some interesting properties of a dot product-type matrix multiplication. Understanding these properties will become useful as you study machine learning. The lab will require you to calculate results to provide a proof for these properties.

## Objectives

In this lab you will: 

- Demonstrate the distributive, commutative, and associative property of dot products 
- Use the transpose method to transpose Numpy matrices 
- Compute the dot product for matrices and vectors 


## Instructions

* For each property, create suitably sized matrices with random data to prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

## Distributive Property - matrix multiplication IS distributive

### Prove that $A \cdot (B+C) = (A \cdot B + A \cdot C) $

In [1]:
import numpy as np

In [6]:
# A will be a 2 x 2 matrix
A = np.array([[1,2], [3,4]])

# B and C will be 2 x 2 matrices
B = np.array([[7,4], [1,8]])
C = np.array([[5,9], [3,2]])

In [7]:
# LHS of equation
A.dot(np.add(B,C))

array([[20, 33],
       [52, 79]])

In [8]:
# RHS of equation
np.add(A.dot(B), A.dot(C))

array([[20, 33],
       [52, 79]])

## Associative Property - matrix multiplication IS associative
### Prove that $A \cdot (B \cdot C) = (A \cdot B) \cdot C $

In [9]:
# LHS of equation
A.dot(B.dot(C))

array([[105, 121],
       [257, 313]])

In [10]:
# RHS of equation
A.dot(B).dot(C)

array([[105, 121],
       [257, 313]])

## Commutative Property - matrix multiplication is NOT commutative
### Prove that for matrices, $A \cdot B \neq B \cdot A $

In [11]:
# LHS of equation
A.dot(B)

array([[ 9, 20],
       [25, 44]])

In [12]:
# RHS of equation
B.dot(A)

array([[19, 30],
       [25, 34]])

## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors,  $x^T \cdot y = y^T \cdot x$
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [13]:
# LHS of equation
A.T.dot(B)

array([[10, 28],
       [18, 40]])

In [14]:
# RHS of equation
B.T.dot(A)

array([[10, 18],
       [28, 40]])

## Simplification of the matrix product
### Prove that $ (A \cdot B)^T = B^T \cdot A^T $

In [15]:
# LHS of equation
A.dot(B).T

array([[ 9, 25],
       [20, 44]])

In [16]:
# RHS of equation
B.T.dot(A.T)

array([[ 9, 25],
       [20, 44]])

## Summary 

You've seen enough matrix algebra by now to solve a problem of linear equations as you saw earlier. You'll now see how to do this next. 